name: Docker Image CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build the Docker image
        env:
          USER: ${{ secrets.USER }}
          PASS: ${{ secrets.PASS }}
        run: |
          docker build -t ankesh28/ankesh-ci-2025:v1 .
      - name: Docker login
        run: |
          echo ${{ secrets.DOCKER_PASS }} | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin
      - name: Push Docker image to Docker Hub
        run: |
          docker push ankesh28/ankesh-ci-2025:v1
